// Les méthodes "GET" permettent de récupérer les infos à l'API (Strapi).

// Les méthodes "POST" permettent d'envoyer des infos à l'API (Strapi).

// "?populate" dans les routes permet de récupérer les données relationnels (ex. : le chanteur dans chaque chanson).

// Attention : le format des dates est "année-mois-jour".

// Attention : quand il y a une relation avec une autre collection, il faut simplement indiquer le numéro de l'ID correspondant à l'enregistrement souhaitée (ex. : faire une "Send Request" des chanteurs pour savoir l'ID du titre de ce chanteur). Strapi converti les champs relationnels en minuscules.

###
GET http://localhost:1337/api/singers

###
GET http://localhost:1337/api/musics?populate=*

###
GET http://localhost:1337/api/musics?filters[Favorite][$eq]=true&populate=*&pagination[limit]=10

// https://docs.strapi.io/dev-docs/api/rest/filters-locale-publication (syntaxe sur la doc de Stapi pour filtrer les résultats d'une requête)

###
GET http://localhost:1337/api/musics?sort=createdAt:desc&pagination[limit]=10

// https://docs.strapi.io/dev-docs/api/rest/sort-pagination#sorting (syntaxe sur la doc de Strapi pour trier les résultats d'une requête)

###
POST http://localhost:1337/api/singers
content-type: application/json

{
    "data": {
        "LastName": "Delpech",
        "FirstName": "Michel",
        "BirthDate": "1946-01-26"
    }
}

###
POST http://localhost:1337/api/musics
content-type: application/json

{
    "data": {
        "Title": "Petit pays",
        "Link": "https://www.youtube.com/watch?v=dTi65qoLjZI",
        "Favorite": false,
        "ReleaseDate": "2004-01-01",
        "BackgroundColor": "#c3c3c3",
        "singer": 2
    }
}

###
POST  http://localhost:1337/api/auth/local
content-type: application/json

{
    "identifier": "jeremyfelix41@gmail.com",
    "password": "Bloupy73!"
}